spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssamantle?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dbstmdgur123!@#

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.pigeon3.ssamantle.adapter.out.rdb.**.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    com.pigeon3.ssamantle.adapter.out.rdb: DEBUG
    org.mybatis: DEBUG
